// ui
export const ActionTypes = {
  SET_DOCUMENT_DRAGGED_OVER: "SET_DOCUMENT_DRAGGED_OVER",
  SET_APP_TOUCHED: "SET_APP_TOUCHED",
  CHANGE_APPLICATION_THEME: "CHANGE_APPLICATION_THEME",
  CHANGE_APPLICATION_LOCALE: "CHANGE_APPLICATION_LOCALE",
  SET_SCROLL_TARGET: "SET_SCROLL_TARGET",
  GITHUB_API_LOADING: "GITHUB_API_LOADING",
  GITHUB_API_SUCCESS: "GITHUB_API_SUCCESS",
  GITHUB_API_FAILURE: "GITHUB_API_FAILURE",
} as const;

export type ActionType = (typeof ActionTypes)[keyof typeof ActionTypes];
